version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
  web:
      build: .
      command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
      environment:
        - RAILS_ENV=${RAILS_ENV}
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_URL=postgres://postgres:${DATABASE_PASSWORD}@db:5432/postgres
      volumes:
        - app-storage:/rails/storage
      ports:
        - "3000:3000"
      depends_on:
        - db
volumes:
  db_pg_data:
  app-storage: